// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktthqjybjbjoskkolhke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dGhxanliamJqb3Nra29saGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTgzNjYsImV4cCI6MjA2OTc3NDM2Nn0.BfCrxNAAaP_AYGLi9NyaQpwR37CMUdTPGkZuOnSnYlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});